# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 10:06
from __future__ import unicode_literals

from django.db import migrations
import lfs.cloud_storage.cloud_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171014_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=lfs.cloud_storage.cloud_fields.CloudImageField(blank=True, max_length=250, null=True),
        ),
    ]
