# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_DeliveryTimeOrder_to_OrderDeliveryTime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
