# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 22:42
from __future__ import unicode_literals

from django.db import migrations
import lfs.cloud_storage.cloud_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171014_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=lfs.cloud_storage.cloud_fields.CloudImageField(null=True),
        ),
    ]
