# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 23:17
from __future__ import unicode_literals

from django.db import migrations
import lfs.cloud_storage.cloud_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_image_cloud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cloud_image',
            field=lfs.cloud_storage.cloud_fields.CloudImageCharField(),
        ),
    ]
