# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 10:24
from __future__ import unicode_literals

from django.db import migrations
import lfs.cloud_storage.cloud_fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20171024_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=lfs.cloud_storage.cloud_fields.CloudImageField(max_length=250, null=True),
        ),
    ]
