# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170216_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price_calculator',
            field=models.CharField(choices=[[b'lfs.gross_price.calculator.GrossPriceCalculator', 'Price includes tax'], [b'lfs.net_price.calculator.NetPriceCalculator', 'Price excludes tax']], default=b'lfs.gross_price.calculator.GrossPriceCalculator', max_length=255, verbose_name='Price calculator'),
        ),
    ]
