# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 11:50
from __future__ import unicode_literals

from django.db import migrations
import lfs.cloud_storage.cloud_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0005_auto_20171025_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=lfs.cloud_storage.cloud_fields.CloudImageField(blank=True, file_name='Image', null=True, upload_to=b'images'),
        ),
    ]
