# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='module',
            field=models.CharField(blank=True, choices=[[b'lfs_paypal.processor.PayPalProcessor', 'PayPal']], max_length=100, verbose_name='Module'),
        ),
    ]
