# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20170216_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price_calculator',
            field=models.CharField(choices=[[b'lfs.shipping.calculator.GrossShippingMethodPriceCalculator', 'Price includes tax'], [b'lfs.shipping.calculator.NetShippingMethodPriceCalculator', 'Price excludes tax']], default=b'lfs.shipping.calculator.GrossShippingMethodPriceCalculator', max_length=200, verbose_name='Price Calculator'),
        ),
    ]
