# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 10:57
from __future__ import unicode_literals

from django.db import migrations
import lfs.cloud_storage.cloud_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20171014_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='image',
            field=lfs.cloud_storage.cloud_fields.CloudImageField(blank=True, null=True, upload_to=b'images', verbose_name='Image'),
        ),
    ]
